### PR TITLE
Better transform

### PR DESCRIPTION
**Pull request by cornguo**
Make text transform looks better

### CODE REVIEW

**Review by hepwori — COMMENTED** [review]
This looks off to me in Chrome 56.0.2924.87 on Mac. I've noticed definite variability between browsers… what are you using where this looks better?

**Comment by cornguo** [comment]
I'm using Chrome, too.  It might a problem caused by font I think?

**Comment by cornguo** [comment]
Ouch, confirmed to be my fault.  I've put the wrong transform parameters to the patch.

**Comment by cornguo** [comment]
I'll send another PR if there's better parameters.  Close ticket.

**Pull request closed without merging**
